### ISSUE TITLE
cannot find symbol for (var storage : defaultCC.getPotentialOutputRegisterStorage(program))

### ISSUE THREAD

**Issue by shijy16** [sgfvamll/gsat#1]
Hi, thanks for the great tool. 
But when I built this tool following the guide, I met the following error:
```
cannot find symbol for (var storage : defaultCC.getPotentialOutputRegisterStorage(program))
```

And I noticed that this API is defined by modifying ghidra, as the following comments state:
```
        /// Need customized ghidra build to provide `getPotentialOutputRegisterStorage`
        /// api.
```

So, would you please provide the modified ghidra jar?

**Comment by sgfvamll** [comment]
Actually, the modified Ghidra jar is provided on the release page. Here is the [link](https://github.com/sgfvamll/gsat/releases/download/v1.0.0/ghidra-withsrc.jar). 
The modified source code is included in the jar as well.

**Comment by shijy16** [comment]
Yeah, I just found it in HermesSim's repo. And I didnot click into the release page of this repo before. 
BTW, the README is kind of misleading as it says:
```
Get a release of [Ghidra](https://github.com/NationalSecurityAgency/ghidra) (Tested on 10.2.3).
```
It leads me to build a fresh ghidra on my own XD. It would be helpful if the README mentions that the ghidra is modified and provided.
Anyway, thanks for the tool, it helps a lot for analyzing ghidra pcode.
